save_step: 5
valid_step: 1
train:
  batch_size: 128
  learning_rate: 0.05
  num_epochs: 50
  step_size: 20
  gamma: 0.1
#save_path: "checkpoints/bbn_model.pth"

data:
  train_file: "../data/jsons/converted_train2019.json"
  val_file: "../data/jsons/converted_val2019.json"
  test_file: "../data/jsons/converted_test2019.json"
  num_classes: 1010
output:
  output_dir: "..data/output"
