save_step: 1
valid_step: 1
COLOR_SPACE: 'RGB'
train:
  num_workers: 2
  batch_size: 256
  learning_rate: 0.05
  num_epochs: 50
  step_size: 20
  gamma: 0.1
#save_path: "checkpoints/bbn_model.pth"

data:
  train_file: "../data/jsons/converted_val2019.json"
  val_file: "../data/jsons/converted_val2019.json"
  test_file: "../data/jsons/converted_test2019.json"
  num_classes: 1010
output:
  output_dir: "../data/models"
