save_step: 1
valid_step: 1
train:
  num_workers: 16
  batch_size: 128
  learning_rate: 0.05
  num_epochs: 90
  step_size: 20
  gamma: 0.1

data:
  train_file: "../data/jsons/converted_train2019.json"
  val_file: "../data/jsons/converted_val2019.json"
  test_file: "../data/jsons/converted_val2019.json"
  num_classes: 1010
output:
  output_dir: "../data/models"
